package theIronYard;

public class SimpleDice {

    public static void main(String[] args) {

	SimpleDice simpledice = new SimpleDice();
	simpledice.addRollvalue();

    }

    //method to add the random number that are generated by rollDice method until 1 is rolled
    public void addRollvalue() {
	int currentRollValue = 0;
	int sumValue = 0;
	int i = 0;
	//a loop to roll the dice 100 times or until 1 is rolled
	for (; i < 100; i++) { 

	    currentRollValue = rollDice();
	    if (currentRollValue != 1) {
		sumValue = sumValue + currentRollValue;
		System.out.println(currentRollValue);

	    }

	    else {

		i = 100;
	    }
	}
	
	System.out.println("Total value until 1 is rolled = " + sumValue);
    }

    //method to generate random number between 1 and 6
    public int rollDice() { 
	int RollValue = 1 + (int) (Math.random() * 6); // generates random value between 1 -6
	return RollValue;

    }

}
